# Generated by Django 3.2.12 on 2022-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('regular', 'Regular'), ('can_wait', 'Can wait'), ('have_to', 'Have to!')], default='regular', max_length=25),
        ),
    ]
